
services:
  mapquiz-mysql:
    image: mysql:8
    container_name: mapquiz-mysql-container
    restart: always
    env_file: 
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - mapquiz-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  mapquiz-network:
    external: true