
services:
  mapquiz-mysql:
    image: mysql:8
    container_name: mapquiz-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mapquizdb         
      MYSQL_USER: user                   
      MYSQL_PASSWORD: password           
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - mapquiz-network

  mapquiz-app:
    build:
      context: ../
      dockerfile: ./MapQuiz-env/Dockerfile
    container_name: mapquiz-node-container
    working_dir: /app

    ports:
      - "3000:3000"
      - "5173:5173"
    command: ["npm", "run", "dev", "--prefix", "backend"]
    depends_on:
      - mapquiz-mysql

    env_file:
      - ../MapQuiz-backend/.env
    networks:
      - mapquiz-network

volumes:
  mysql_data:

networks:
  mapquiz-network:
        driver: bridge
