
services:
  mapquiz-mysql:
    image: mysql:8
    container_name: mapquiz-mysql-container
    restart: always
    env_file: 
      - .env.db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - mapquiz-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  mapquiz-node:
    build:
      context: .  # backendディレクトリをビルド対象に
      dockerfile: Dockerfile
    container_name: mapquiz-node-container
    working_dir: /app
    volumes:
      - ../MapQuiz-backend:/app  # バックエンドコードをマウント
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      mapquiz-mysql:
        condition: service_healthy
    env_file:
      - .env.backend
    networks:
      - mapquiz-network

volumes:
  mysql_data:

networks:
  mapquiz-network:
        driver: bridge
